apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: talker
  namespace: prod
spec:
  meshName: greeting-app
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  serviceDiscovery:
    dns:
      hostName: talker.prod.svc.cluster.local
  backends:
    - virtualService:
        virtualServiceName: mostly-hello.prod.svc.cluster.local
    - virtualService:
        virtualServiceName: mostly-howdy.prod.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: hello
  namespace: prod  
spec:
  meshName: greeting-app
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  serviceDiscovery:
    dns:
      hostName: hello.prod.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: howdy
  namespace: prod
spec:
  meshName: greeting-app
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  serviceDiscovery:
    dns:
      hostName: howdy.prod.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: mostly-howdy
  namespace: prod
spec:
  meshName: greeting-app
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  serviceDiscovery:
    dns:
      hostName: mostly-howdy.prod.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: mostly-hello
  namespace: prod
spec:
  meshName: greeting-app
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  serviceDiscovery:
    dns:
      hostName: mostly-hello.prod.svc.cluster.local

